### ISSUE TITLE
New qtrcl pip install problems

### ISSUE THREAD

**Issue by EeshGupta** [qctrl/.github#45]
Installed qtrl via 

pip install qtrl 

(Most recent release : October 2, 2023)

- Corrupted my environment
- Can't open jupyter notebook (get 500 internal error)

**Comment by luigibertaco** [comment]
Hi @EeshGupta,

Thank you for sharing the issue. For support requests, you can submit via our contact page at https://q-ctrl.com/contact.

To speed up resolution, please include in your submission your Python version, OS details, if you are using a virtual environment and the version of the `qctrl` package you have installed.

Regards
